echo Teams Restarter
echo Closing Microst Teams
echo Waiting For Teams to Close....
echo ..
echo ...
echo ....
echo .....
echo ......
echo .......
taskkill /im teams.exe /f
echo Closed Microsft Teams
echo Restarting Microsoft Teams
C:\Users\pranit\AppData\Local\Microsoft\Teams\Update.exe --processStart "Teams.exe"
echo Waiting For Teams to Open.‎..
echo ..
echo ...
echo ....
echo .....
echo ......
echo .......
echo Restarted Microsoft Teams
echo Closing Cmd Window.
taskkill /im cmd.exe /f


